# Generated by Django 5.2.7 on 2025-10-07 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly'), (60, 'Bimonthly'), (90, 'Quarterly'), (180, 'Biannual'), (360, 'Annual')], default=30)),
                ('observations', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('L', 'Locked'), ('I', 'Inactive'), ('C', 'Canceled')], default='A', max_length=1)),
                ('observations', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Members')), on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.plans')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
