# Generated by Django 5.2.7 on 2025-10-07 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_frequency', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly'), (60, 'Bimonthly'), (90, 'Quarterly'), (180, 'Biannual'), (360, 'Annual')], default=30)),
                ('observations', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
