# Generated by Django 5.2.7 on 2025-11-10 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('sector', models.CharField(choices=[('Almoxarifado', 'Almoxarifado'), ('Comercial', 'Comercial'), ('Controle', 'Controle'), ('Compras', 'Compras'), ('Contabilidade', 'Contabilidade'), ('Custos', 'Custos'), ('Diretoria', 'Diretoria'), ('Engenharia', 'Engenharia'), ('Financeiro', 'Financeiro'), ('Fiscal', 'Fiscal'), ('Gestão de Pessoas', 'Gestão de Pessoas'), ('Gestão Industrial', 'Gestão Industrial'), ('Industria de Apontamento', 'Industria de Apontamento'), ('Industria de Eletrônicos', 'Industria de Eletrônicos'), ('Industria de Esferas', 'Industria de Esferas'), ('Industria Metalúrgica', 'Industria Metalúrgica'), ('Industria de Placas', 'Industria de Placas'), ('Industria de Tachas', 'Industria de Tachas'), ('Industria de Tintas', 'Industria de Tintas'), ('Jurídico', 'Jurídico'), ('Licitação', 'Licitação'), ('Logística', 'Logística'), ('Manutenção', 'Manutenção'), ('Marketing', 'Marketing'), ('Monitoramentos', 'Monitoramentos'), ('Obras', 'Obras'), ('Projetos', 'Projetos'), ('Qualidade', 'Qualidade'), ('Recebimentos', 'Recebimentos'), ('Recursos Humanos', 'Recursos Humanos'), ('Secretaria', 'Secretaria'), ('Segurança do Trabalho', 'Segurança do Trabalho'), ('Tecnologia', 'Tecnologia'), ('Trânsito', 'Trânsito')], max_length=150)),
                ('metabase_code', models.IntegerField(blank=True, null=True)),
                ('powerbi_url', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'Em Desenvolvimento'), ('M', 'Em Manutenção'), ('F', 'Em Funcionamento')], default='D', max_length=1)),
                ('fav_by', models.ManyToManyField(blank=True, related_name='favorited_dashboards', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='dashboards', to='auth.group')),
                ('users', models.ManyToManyField(blank=True, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['sector', 'title'],
                'permissions': [('view_all_dashboards', 'Can view all dashboards')],
            },
        ),
    ]
