# Generated by Django 5.2.7 on 2025-10-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Pending'), ('L', 'Locked'), ('C', 'Canceled'), ('F', 'Finished')], default='D', max_length=1)),
                ('observations', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(limit_choices_to={'groups__name': 'Members', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='app.plans')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
