# Generated by Django 5.2.7 on 2025-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dashboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='dashboards',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='app.dashboards'),
        ),
    ]
