# Generated by Django 5.2.7 on 2025-10-22 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('L', 'Late'), ('C', 'Canceled'), ('S', 'Paid'), ('R', 'Refunded')], default='P', max_length=1)),
                ('observations', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(limit_choices_to=models.Q(('status', 'A'), ('status', 'P'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.contracts')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
