# Generated by Django 5.2.7 on 2025-11-16 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dashboards_users_users_dashboards'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='groups',
        ),
        migrations.CreateModel(
            name='GroupDashboards',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.group')),
                ('dashboards', models.ManyToManyField(blank=True, related_name='assigned_groups', to='app.dashboards')),
            ],
        ),
    ]
