# Generated by Django 5.2.7 on 2025-11-16 23:22

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_dashboards_groups_groupdashboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[app.validators.unique_email]),
        ),
    ]
