# Generated by Django 5.2.7 on 2025-11-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='metabase_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
