# Generated by Django 5.2.7 on 2025-11-16 23:43

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dashboards_metabase_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='powerbi_url',
            field=models.CharField(blank=True, null=True, validators=[app.validators.valid_url]),
        ),
    ]
